/**
 * Minimal projection of bindings generated by:
 * codex-cli 0.144.5 app-server generate-json-schema
 *
 * Keep this projection pinned with the binary; unknown notification fields stay opaque.
 */
export const CODEX_CLI_VERSION = "0.144.5";
export const CODEX_PROTOCOL_REVISION = "app-server-json-schema-0.144.5";

/**
 * 已逐项核对协议表面一致的 codex 版本（`app-server generate-json-schema` 比对：
 * initialize / thread.start / turn.start / turn.interrupt、两个 requestApproval 方法、
 * sandbox 模式、审批决定枚举——均无变化）。ChatGPT.app 会自动升级 codex 到新的 alpha 版，
 * 因此这里用「已验证兼容集合」而不是单一精确版本；未知版本仍拒绝（除非显式放行，见 isCompatibleCodexVersion 调用点）。
 */
export const CODEX_COMPATIBLE_VERSIONS = ["0.144.5", "0.145.0-alpha.30"] as const;

export function isCompatibleCodexVersion(version: string | null | undefined): boolean {
  return !!version && (CODEX_COMPATIBLE_VERSIONS as readonly string[]).includes(version);
}

export type CodexSandboxMode = "read-only" | "workspace-write";
export type CodexApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

export interface CodexThreadStartResponse {
  thread: { id: string; [key: string]: unknown };
  cwd: string;
  model: string;
  modelProvider: string;
  [key: string]: unknown;
}

export interface CodexTurnStartResponse {
  turn: { id: string; status: string; [key: string]: unknown };
}

export interface CodexApprovalRequest {
  id: string | number;
  method: "item/commandExecution/requestApproval" | "item/fileChange/requestApproval" | string;
  params: Record<string, unknown>;
}
