/**
 * Minimal projection of bindings generated by:
 * codex-cli 0.144.5 app-server generate-json-schema
 *
 * Keep this projection pinned with the binary; unknown notification fields stay opaque.
 */
export const CODEX_CLI_VERSION = "0.144.5";
export const CODEX_PROTOCOL_REVISION = "app-server-json-schema-0.144.5";

export type CodexSandboxMode = "read-only" | "workspace-write";
export type CodexApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

export interface CodexThreadStartResponse {
  thread: { id: string; [key: string]: unknown };
  cwd: string;
  model: string;
  modelProvider: string;
  [key: string]: unknown;
}

export interface CodexTurnStartResponse {
  turn: { id: string; status: string; [key: string]: unknown };
}

export interface CodexApprovalRequest {
  id: string | number;
  method: "item/commandExecution/requestApproval" | "item/fileChange/requestApproval" | string;
  params: Record<string, unknown>;
}
